# Generated by Django 5.2.5 on 2025-08-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_alter_complaint_id_alter_grievance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
